### ISSUE TITLE
Add example code and instructions for an overlay style search interface

### ISSUE THREAD

**Issue by mish15** [sajari/sajari-sdk-react#35]
Should by default be designed for web collections. Core base features to include:

- [ ] overlay base css
- [ ] overlay animate in on trigger
- [x] logo left on desktop, on top on mobile style layout, click logo to exit
- [x] close button in top right
- [x] search box in top bar
- [x] results rendering in main section under top bar
- [ ] esc to exit

And:
- [ ] readme explaining how to build and release.
- [ ] add animated gif showing what it does in action

**Comment by mish15** [comment]
@tbillington i think most of this is done now?

**Comment by tbillington** [comment]
There is an example but it needs a little bit more work. https://github.com/sajari/sajari-sdk-react/tree/master/examples/overlay.

**Comment by mish15** [comment]
@tbillington can we close this out as we put up the other example?

**Comment by mish15** [comment]
Done. See: https://github.com/sajari/website-search-integration
