### ISSUE TITLE
Expose set of events which are triggered during search sessions.

### ISSUE THREAD

**Issue by dhowden** [sajari/sajari-sdk-react#36]
Initially we want to define events for:
- Body change
- Search
- Click
- Reset (request query ID).

There also needs to be functions in the library that can be used to register/deregister event listeners.

**Comment by dhowden** [comment]
@tbillington Seems to be related to #52,  maybe close this and add more info there.

Also need to make sure that this is properly documented.

**Comment by tbillington** [comment]
Click & Reset are in `state.js` now, there are methods to register listeners.

As for the rest, closing in favour of https://github.com/sajari/sajari-sdk-react/issues/52.
