### ISSUE TITLE
Change summary to provide more information

### ISSUE THREAD

**Issue by mish15** [sajari/sajari-sdk-react#53]
When a search is being autocompleted, the user can hit enter to override the autocomplete and run the exact text in the input box. This is ok, but can confuse the user if they aren't aware they can hit enter. 

So:
- [x] Wrap the timing component in a span so it can be hidden if desired
- [x] We don't need 6 decimal places in the timing. So 0.000444 should be 0.0004. And 0.044 should be 0.04 etc. 
- [x] Change summary when the query run does not equal the query in the box to also include "Hit enter to search for X", where X is the original search. X should also be a link, that performs the same functionality.

**Comment by dhowden** [comment]
The timing part is being handled in #80

**Comment by dhowden** [comment]
Timing part completed in #80.
