### ISSUE TITLE
component: autocomplete dropdown

### ISSUE THREAD

**Issue by mish15** [sajari/sajari-sdk-react#63]
- [x] should use the `autocomplete` pipeline and render the top X results in a dropdown under the query input. Note: could also do this with a query, so plan for both.
- [x] X should be configurable
- [ ] The destination should be configurable (i.e. send to another page: results?q=xyz or run a search in the app and render the results on the current page)

**Comment by mish15** [comment]
@tbillington did this get completed?

**Comment by tbillington** [comment]
^ Yes :)
