### ISSUE TITLE
paging: when on page > 1 and adding a filter, the page does not reset

### ISSUE THREAD

**Issue by mish15** [sajari/sajari-sdk-react#68]
If say on page 4 and a filter is added such that there are no longer 4 pages of results, page 4 is still shown, but obviously has no results. The page number should reset when the filters are changed

**Comment by mish15** [comment]
cc @jrhodes-sitback

**Comment by dhowden** [comment]
See https://github.com/sajari/sajari-sdk-react/blob/master/examples/standard-search/src/App.js#L23

**Comment by mlhoque** [comment]
Need to add the page reset to 1 in the filter listener e.g. 

`categoryFilter.listen(selectionUpdatedEvent, () => {
  
  values.set({ page: "1" });
  pipeline.search(values);
});`

**Comment by mish15** [comment]
@mlhoque @jrhodes-sitback you need to update your version.

**Comment by sampotts** [comment]
This issue seems to be present in the example:
https://sajari-sdk-react.netlify.com/example

Search for a term with a lot of pages, page through and then change term to something with a few pages. It gets stuck.

**Comment by benhinchley** [comment]
@sampotts thanks for spotting this, I'll get a fix into the example code now.

For reference to solve that issue, you can use the following snippet of code:
```js
values.listen(EVENT_VALUES_UPDATED, (changes, set) => {
  if (!changes.page) {
    set({ page: "1" });
  }
});
```
