### ISSUE TITLE
suggestions: css changes to prevent being hidden

### ISSUE THREAD

**Issue by tbillington** [sajari/sajari-sdk-react#83]
Suggestions appearing under the search box are often hidden by elements down the page who use special positioning. To escape this we can set position:fixed on the outer most element of the UI. This breaks the responsiveness of the UI. To combat this we can observe the size of the parent of the outer most element and resize appropriately using javascript.

Possible implementation: https://github.com/que-etc/resize-observer-polyfill.

**Comment by benhinchley** [comment]
This has been fixed as of [v2.0](https://github.com/sajari/sajari-sdk-react/releases/tag/v2.0.0)
