### ISSUE TITLE
Add AggregateFilter controller

### ISSUE THREAD

**Issue by benhinchley** [sajari/sajari-sdk-react#91]
We currently have the `Filter` class which acts as a convenience around creating and manipulating filters in the search interface. There is currently nothing that does the same for **Facets** (filters created from aggregates). Bellow is the source of a custom `CountAggegrateFilter` and `DateAggregateFilter` I built for a project, would be nice to have a series of these in the SDK for the different aggregate types (count, date) as well as a generic one.

```js
/*
 * CountAggregateFilter
 */
export class CountAggregateFilter extends Filter {
  _field = "";
  _counts = [];
  _multi = false;

  constructor(field, pipeline, multi = false, type = "~") {
    super({}, [], multi);

    this._field = field;
    this._multi = multi;

    pipeline.listen(responseUpdatedEvent, response => {
      const current = this.get();
      const aggregates = response.getAggregates();

      this._counts = this._getCounts(aggregates);
      this._clearFilterOptions(current);
      this.setOptions(this._genFilterOptions(current, type));
    });
  }

  _getCounts(aggregates) {
    if (isEmpty(aggregates, this._field)) return [];

    const counts = aggregates[`count.${this._field}`]["count"]["counts"];
    return Object.keys(counts)
      .map(key => {
        return { name: key, count: counts[key] };
      })
      .filter(x => x.name !== "")
      .sort(({ count: a }, { count: b }) => b - a);
  }

  _genFilterOptions(current, type = "~") {
    return this._counts.reduce((opts, { name, count }) => {
      if (!current.includes(name)) {
        opts[name] = `${this._field}${type}"${name}"`;
      }
      return opts;
    }, {});
  }

  _clearFilterOptions(current) {
    const clear = Object.keys(this.getOptions()).reduce((opts, key) => {
      if (!current.includes(key)) {
        opts[key] = undefined;
      }
      return opts;
    }, {});
    this.setOptions(clear);
  }
}

const isEmpty = (aggregates, field) =>
  !aggregates ||
  !aggregates[`count.${field}`] ||
  !aggregates[`count.${field}`]["count"] ||
  !aggregates[`count.${field}`]["count"]["counts"];
```

```js
/*
 * DateAggregateFilter
 */
export class DateAggregateFilter extends Filter {
  _field = "";
  _counts = [];
  _multi = false;
  _range = [0, 0];
  _filter = "";
  _current = "";

  constructor(field, pipeline, multi = false, type = "~") {
    super({}, [], multi);

    this._field = field;
    this._multi = multi;

    pipeline.listen(responseUpdatedEvent, response => {
      const aggregates = response.getAggregates();
      if (isEmpty(aggregates, this._field)) return;

      this._counts = this._getCounts(aggregates);
      this._range = [
        this._counts[0],
        this._counts[this._counts.length - 1]
      ].map(({ name }) => parseInt(name, 10));

      this._emitOptionsUpdated();
    });
  }

  range = () => this._range;
  counts = () => this._counts;
  filter = () => this._filter;

  get = () => (this._current === "" ? [] : [this._current]);

  set = (from, to) => {
    const fromTimestamp = (new Date(`${from}.01.01`).getTime() / 1000).toFixed(
      0
    );
    const toTimestamp = (new Date(`${to}.12.31`).getTime() / 1000).toFixed(0);

    if (!isNaN(fromTimestamp) && !isNaN(toTimestamp)) {
      this._filter = `(${this._field} >= ${fromTimestamp} AND ${
        this._field
      } <= ${toTimestamp})`;

      this._current = `${from} - ${to}`;
    }

    this._emitSelectionUpdated();
  };

  clear = () => {
    this._filter = "";
    this._current = "";
    this._emitSelectionUpdated();
  };

  _getCounts(aggregates) {
    const counts = aggregates[`date.${this._field}`]["date"]["dates"];
    return Object.keys(counts)
      .map(key => {
        return { name: key, count: counts[key] };
      })
      .filter(x => x.name !== "")
      .sort(({ name: a }, { name: b }) => a - b);
  }
}

const isEmpty = (aggregates, field) =>
  !aggregates ||
  !aggregates[`date.${field}`] ||
  !aggregates[`date.${field}`]["date"] ||
  !aggregates[`date.${field}`]["date"]["dates"];
```

**Comment by zlatanpham** [comment]
Hey @benhinchley, I just have few questions for the tickets: 
- Is the path like `[date.${field}]["date"]["dates"]` stable or unpredictable?
- Is there any piece of UI behind `DateAggregateFilter` to look at? I don't really understand what the code do.
- Since the sample codes of `CountAggregateFilter` & `DateAggregateFilter` look different, what do you expect for output of a generic?

**Comment by benhinchley** [comment]
Hey @zlatanpham for the this path `[date.${field}]["date"]["dates"]` I am actually unsure if that is stable, so maybe just work on the count variant for the moment, while I check in with @dhowden.

* I'll try find the UI code the the DateAggregate stuff and post here or in a gist depending on its size.
* And yes good point, I am not 100% sure at the moment what the generic controller would look like. We can probably discuss this a at a later point

**Comment by zlatanpham** [comment]
Hey @benhinchley, just finish the [CountAggregateFilter](https://github.com/sajari/sajari-sdk-react/compare/master...zlatanpham:aggregate-filter-controller). Basically, it was just a transformation of your code into `ts`. Hope you can give some feedback.

**Comment by benhinchley** [comment]
@zlatanpham this looks good.

Been thinking about this for a bit and not sure if it is worth doing, but it is very easy to forget to add the `"count": "<field_name>"` to the values object when using a Count aggregate. I'm wondering if it is worth adding the values object as an argument to the constructor, and then subscribing to the `EVENT_VALUES_UPDATED` event, and on change add the `"count": "<field_name>"` to the values object.

**Comment by zlatanpham** [comment]
@benhinchley like this?
```js
const fieldNameFilter = new CountAggregateFilter('field_name');
const values = new Values({
  fields: '',
  count: 'field_name',
});
```
If so, I also think it makes sense to force passing `values` object to the filter.

**Comment by benhinchley** [comment]
@zlatanpham yep that is exactly what you would have to do now.
So yeah I think it makes sense to change the constructor to be
```js
let fieldNameAggregate = CountAggregateFilter("field_name", pipeline, values);
```

**Comment by zlatanpham** [comment]
@benhinchley, please help me review the [update](https://github.com/sajari/sajari-sdk-react/compare/master...zlatanpham:aggregate-filter-controller).

**Comment by benhinchley** [comment]
@zlatanpham this looks okay, can you make a PR against this repo so I can review more easily
