### ISSUE TITLE
Create `Downshift` style component for the search input

### ISSUE THREAD

**Issue by benhinchley** [sajari/sajari-sdk-react#92]
[`Downshift`][DownshiftGithub] is used internally for the `<Input />` component, and one of the things I really like about the [`Downshift`][DownshiftGithub] implementation is how it doesn't actually render anything itself, it passes through control of the HTML rendering to the end user, but abstracts and simplifies the business case of creating autocomplete/dropdown components.

It would be nice to abstract the business logic of our `<Input />` component into something similar to how [`Downshift`][DownshiftGithub] operates to make it easier for end users to provide their own markup and implementation of the search input.

Reference: [Downshift Usage](https://github.com/paypal/downshift#usage)

[DownshiftGithub]: https://github.com/paypal/downshift

**Comment by zlatanpham** [comment]
@benhinchley, but we still need to keep the old render code and only add logic to do `render prop` if `children` provided?

**Comment by benhinchley** [comment]
@zlatanpham yep so the old render code I guess we could make that it's own component that we provide to a default input component, as the children of the new `<Input />` render prop

**Comment by zlatanpham** [comment]
@benhinchley, my first thought was something like this
```jsx
// Return default input component
<Input style=... theme=.../>

// Provide logic via inputProps, and free to construct the view
<Input>
{ inputProps => <AnyComponent/>}
</Input>
```
But if we could build an entirely new Input borrowed the Downshift's concepts like `stateReducer`, then the end result would be like this:
```jsx
<NewInput>
{ inputProps => <AnyComponent/>}
</NewInput>
```

**Comment by benhinchley** [comment]
@zlatanpham I'm liking the second idea more, just cause it allows for much more flexibility. 
The one big issue with the current version is it is very hard to change the implementation underneath, and rather than adding more props to make it more customisable, it seems like a better idea to abstract all the no UI stuff up into a new component and pass control props etc down like `Downshift`

**Comment by zlatanpham** [comment]
@benhinchley, I'm working on the second idea. Will give you a demo to look at soon.

**Comment by benhinchley** [comment]
@zlatanpham I really like this approach, and the examples are a pretty straightforward. 

It would be interesting to see how the default `<Input />` implementation would look internally using this setup over what it is currently implemented with, especially to see if anything might need to be changed with the new HOF.

**Comment by zlatanpham** [comment]
@benhinchley yep, rebuilding the old `Input` with the new approach might give some useful feedback.

Will post the code once finished.

**Comment by zlatanpham** [comment]
@benhinchley, [here](https://github.com/sajari/sajari-sdk-react/compare/master...zlatanpham:search-render-prop#diff-a795cfbf5ddddca8d4c1c79b87b7634a) is the clone of `Input` using `Search` render prop plus the [demo](https://codesandbox.io/s/l49p258w09).
