### ISSUE TITLE
Create map based search results view

### ISSUE THREAD

**Issue by alexluscombe** [sajari/sajari-sdk-react#99]
Create map based search results view that can plot a geo-location associated with a search result and show it on a map e.g. Google Maps.

![image](https://user-images.githubusercontent.com/35442403/50427379-94a1f900-08fa-11e9-92e5-a529844e82ea.png)

**Comment by zlatanpham** [comment]
Hey @alexluscombe, I've created a [prototype](https://sajari-map-search-result-view.netlify.com/) for the component. At the moment, it accepts to pass `mapOptions` to custom map styles and `Marker` for rendering marker view. Let me know if is there anything you need me to add or update.

**Comment by benhinchley** [comment]
Hey @zlatanpham this demo looks good, could you create a PR with the code so I can give it a look. Thanks :)

**Comment by zlatanpham** [comment]
@benhinchley, sure. There are some work to do with the `typing`, I'll submit the PR once finished.

**Comment by benhinchley** [comment]
closing in favour of #101
